#spring.cloud.zookeeper.config.enable=true;
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9091
spring:
  application:
    name: liapi
  #注册中心的地址
hystrix:
  command:
    userAdd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000